// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaS4Lf0HdSNf3J8UBxDfuytP_i_ALoKPU',
    appId: '1:159036836616:web:e4df9bfc8d1815ed3b3abd',
    messagingSenderId: '159036836616',
    projectId: 'budget-man-2d0a7',
    authDomain: 'budget-man-2d0a7.firebaseapp.com',
    storageBucket: 'budget-man-2d0a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcheO68KB76i1t_bCTvnku61Pghncxsww',
    appId: '1:159036836616:android:b63e604703b84d753b3abd',
    messagingSenderId: '159036836616',
    projectId: 'budget-man-2d0a7',
    storageBucket: 'budget-man-2d0a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2frGyHzYmdN4E8C7wdDjcV4OIJe00A8M',
    appId: '1:159036836616:ios:5f11190acfb72d633b3abd',
    messagingSenderId: '159036836616',
    projectId: 'budget-man-2d0a7',
    storageBucket: 'budget-man-2d0a7.appspot.com',
    iosClientId: '159036836616-h8b7hme80b18c64af1nutg9lde6kg0f0.apps.googleusercontent.com',
    iosBundleId: 'com.budget.budget.RunnerTests',
  );

}